// Code generated by protoc-gen-go.
// source: tcpd.proto
// DO NOT EDIT!

/*
Package tcpd_proto is a generated protocol buffer package.

It is generated from these files:
	tcpd.proto

It has these top-level messages:
	TcpdTest
*/
package tcpd_proto

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type TcpdTest struct {
	Uid              *uint64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Msg              *string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TcpdTest) Reset()         { *m = TcpdTest{} }
func (m *TcpdTest) String() string { return proto.CompactTextString(m) }
func (*TcpdTest) ProtoMessage()    {}

func (m *TcpdTest) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *TcpdTest) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func init() {
}
